version: '3.8'

services:
  oba_bundler:
    build:
      context: .
      dockerfile: Dockerfile  # Referencing the Dockerfile in the root directory
    volumes:
      - ./bundle:/bundle
    environment:
      - GTFS_URL=${GTFS_URL:-default_value}  # Ensure GTFS_URL is set, default if needed

  oba_database_pg:
    image: postgres:16
    container_name: oba_database_pg
    environment:
      POSTGRES_USER: oba_user
      POSTGRES_PASSWORD: oba_password
      POSTGRES_DB: oba_database
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
    restart: always

  oba_app:
    container_name: oba_app
    depends_on:
      - oba_database_pg
    build:
      context: .
      dockerfile: Dockerfile  # Referencing the Dockerfile in the root directory
    environment:
      - JDBC_URL=jdbc:postgresql://oba_database_pg:5432/oba_database
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USER=oba_user
      - JDBC_PASSWORD=oba_password
      - TEST_API_KEY=${TEST_API_KEY:-test}  # Ensure TEST_API_KEY is set, default if needed
      - TZ=America/Los_Angeles
    volumes:
      - ./bundle:/bundle
    ports:
      - "8080:8080"
      - "1234:1234" # JMX exporter port
    restart: always

volumes:
  pg-data:
