apiVersion: v1
kind: Namespace
metadata:
  name: oba
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oba-database-deployment
  namespace: oba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oba-database
  template:
    metadata:
      labels:
        app: oba-database
    spec:
      containers:
      - name: oba-database
        image: postgres:latest  # Switch to PostgreSQL image
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oba-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            value: oba_user
          - name: POSTGRES_DB
            value: oba_database
        ports:
          - containerPort: 5432  # Use PostgreSQL default port (5432)
---
apiVersion: v1
kind: Service
metadata:
  name: oba-database
  namespace: oba
spec:
  selector:
    app: oba-database
  ports:
    - protocol: TCP
      port: 5432   # Match PostgreSQL port (5432)
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oba-app-deployment
  namespace: oba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oba-app
  template:
    metadata:
      labels:
        app: oba-app
    spec:
      initContainers:
        - name: oba-bundler
          image: oba/bundler:test
          env:
            - name: GTFS_URL
              valueFrom:
                configMapKeyRef:
                  name: oba-configs
                  key: GTFS_URL
          volumeMounts:
            - mountPath: /bundle
              name: bundle-volume
      containers:
        - name: oba-app
          image: oba/app:test
          env:
            - name: JDBC_URL
              value: jdbc:postgresql://oba-database.oba.svc.cluster.local:5432/oba_database  # Update JDBC URL for PostgreSQL
            - name: JDBC_USER
              value: oba_user
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oba-secrets
                  key: JDBC_PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /bundle
              name: bundle-volume
      volumes:
        - name: bundle-volume
          emptyDir: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: oba-secrets
  namespace: oba
type: Opaque
data:
  POSTGRES_PASSWORD: b2JhX3Bhc3N3b3Jk  # Updated for PostgreSQL password
  JDBC_PASSWORD: b2JhX3Bhc3N3b3Jk    # Same password for JDBC connection
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oba-configs
  namespace: oba
data:
  GTFS_URL: https://unitrans.ucdavis.edu/media/gtfs/Unitrans_GTFS.zip
